# Use an official Node runtime as the base image
FROM node:20

# Set the working directory in the container
WORKDIR /client

# Copy package.json and yarn.lock
COPY package*.json yarn.lock ./

# Remove node_modules and yarn.lock if they exist
RUN rm -rf node_modules yarn.lock

# Install all dependencies, including optional ones
RUN yarn install --frozen-lockfile --ignore-optional

# Copy the rest of the application code
COPY . .

# Expose port 5173
EXPOSE 5173

# Start the app in development mode
CMD ["yarn", "dev"]